// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-fPVmSnrO4fTknAZqKSx5w2GsG4P7D-M',
    appId: '1:116238447250:web:f1e0303ac9990c7dd52c4b',
    messagingSenderId: '116238447250',
    projectId: 'seccione-c9383',
    authDomain: 'seccione-c9383.firebaseapp.com',
    storageBucket: 'seccione-c9383.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWo1iqUIQEdh_M5G2fbZBL6zSJFlfBUg8',
    appId: '1:116238447250:android:58262d52152afe4bd52c4b',
    messagingSenderId: '116238447250',
    projectId: 'seccione-c9383',
    storageBucket: 'seccione-c9383.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiFImowXFTKeQmC9RAybX_OgULK59rktY',
    appId: '1:116238447250:ios:658dac881ef06f7ad52c4b',
    messagingSenderId: '116238447250',
    projectId: 'seccione-c9383',
    storageBucket: 'seccione-c9383.appspot.com',
    iosClientId: '116238447250-8r9hgpb4hprrlbq8i35d9if2ou0m14ge.apps.googleusercontent.com',
    iosBundleId: 'com.example.ejemplo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiFImowXFTKeQmC9RAybX_OgULK59rktY',
    appId: '1:116238447250:ios:33bf70b5ff9bd763d52c4b',
    messagingSenderId: '116238447250',
    projectId: 'seccione-c9383',
    storageBucket: 'seccione-c9383.appspot.com',
    iosClientId: '116238447250-oite2s979aniabndn3ako19p3vmtndmj.apps.googleusercontent.com',
    iosBundleId: 'com.example.ejemplo.RunnerTests',
  );
}
